<?php
/**
 * Responsible for generating the WXR XML from the data in WP_WXR_Export
 */
class WP_WXR_XML_Generator {
	function __construct( $export ) {
		$this->export = $export;
	}

	static function get_parts() {
		return array( 'header', 'site_metadata', 'authors', 'categories', 'tags', 'nav_menu_terms', 'other_terms', 'posts', 'footer', );
	}

	function header() {
		$wxr_version = WXR_VERSION;
		$charset = $this->export->charset();
		$wp_generator_tag = $this->export->wp_generator_tag();
		return <<<XML
<?xml version="1.0" encoding="$charset" ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->
$wp_generator_tag
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/$wxr_version/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/$wxr_version/"
>
<channel>

XML;
	}

	function site_metadata() {
		$metadata = $this->export->site_metadata();
		return <<<XML
	<title>{$metadata['name']}</title>
	<link><?php bloginfo_rss( 'url' ); ?></link>
	<description><?php bloginfo_rss( 'description' ); ?></description>
	<pubDate><?php echo date( 'D, d M Y H:i:s +0000' ); ?></pubDate>
	<language><?php bloginfo_rss( 'language' ); ?></language>
	<wp:wxr_version><?php echo WXR_VERSION; ?></wp:wxr_version>
	<wp:base_site_url><?php echo wxr_site_url(); ?></wp:base_site_url>
	<wp:base_blog_url><?php bloginfo_rss( 'url' ); ?></wp:base_blog_url>

XML;
	}

	function authors() {
	}

	function categories() {
	}

	function tags() {
	}

	function nav_menu_terms() {
	}

	function other_terms() {
	}

	function posts() {
		return array( 'a', 'b' );
	}

	function footer() {
		return <<<XML
</channel>
</rss>
XML;
	}
}
